### ISSUE TITLE
网站配置忘记改了

### ISSUE THREAD

**Issue by overtrue** [meolu/docs#1]
统计代码与搜索引擎账号是我的呢：https://github.com/meolu/docs/blob/master/_config.yml#L33-L34

QQ 还是我的哈哈: https://github.com/meolu/docs/blob/master/_config.yml#L37

https://easywechat.org

:smile:

**Comment by crazyLQ** [comment]
楼上怪蜀黍....

**Comment by meolu** [comment]
感谢提醒：）

**Comment by overtrue** [comment]
@meolu 所以还是没改啊 😭
